# Autogenerated from /home/jhlou/data/AgentCompiler/adora-compiler/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import os

config.adora_obj_root = r"/home/jhlou/data/AgentCompiler/adora-compiler"
config.adora_src_root = r"/home/jhlou/data/AgentCompiler/adora-compiler/test/.."

# Tool dirs
config.adora_tools_dir = r"/home/jhlou/data/AgentCompiler/adora-compiler/bin"
config.llvm_tools_dir  = r"/home/share/onnx-mlir/third_party/llvm-project-onnx/build/./bin"
config.llvm_shlib_ext  = r""

# Load the main lit config
lit_config.load_config(config, os.path.join(config.adora_src_root, "test", "lit.cfg.py"))
