//===- BufferReuse.cpp - Eliminate redundant BlockStore/BlockLoad pairs ---===//
//
// PR4 commit E.
//
// After adora-schedule-tasks threads !ADORA.token deps, a
//   %loaded = ADORA.BlockLoad async [%tok] %global [map] ...
// where %tok comes from
//   %tok = ADORA.BlockStore %local, %global [map] ... -> !ADORA.token
// can be replaced with %local directly (data stays on-chip).
//
// Must run after adora-schedule-tasks="emit-token=true" and before
// adora-lower-async-tokens.
//===----------------------------------------------------------------------===//

#include "ADORA/Dialect/ADORA/IR/ADORA.h"
#include "ADORA/Dialect/ADORA/Transforms/DependencyAnalysis.h"
#include "ADORA/Dialect/ADORA/Transforms/Passes.h"
#include "ADORA/Dialect/ADORA/Utility/Utility.h"
#include "./PassDetail.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"

using namespace mlir;
using namespace mlir::ADORA;

namespace {

struct EliminateRedundantBlockLoad
    : public OpRewritePattern<DataBlockLoadOp> {
  using OpRewritePattern::OpRewritePattern;

  LogicalResult matchAndRewrite(DataBlockLoadOp load,
                                PatternRewriter &rewriter) const override {
    ValueRange deps = getAsyncDeps(load.getOperation());
    if (deps.size() != 1)
      return failure();

    Value tok = deps[0];
    auto store = dyn_cast_or_null<DataBlockStoreOp>(tok.getDefiningOp());
    if (!store)
      return failure();

    if (!AccessSameDataBlock(store, load))
      return failure();

    // Replace the load result with the store's source (on-chip LocalMemAlloc).
    rewriter.replaceAllUsesWith(load.getResult(), store.getSourceMemref());
    rewriter.eraseOp(load);
    return success();
  }
};

// Use BufferReuseBase generated by PassDetail.h (GEN_PASS_CLASSES).
struct BufferReusePass : public BufferReuseBase<BufferReusePass> {
  void runOnOperation() override {
    RewritePatternSet patterns(&getContext());
    patterns.add<EliminateRedundantBlockLoad>(&getContext());
    (void)applyPatternsAndFoldGreedily(getOperation(), std::move(patterns));
  }
};

} // namespace

std::unique_ptr<OperationPass<func::FuncOp>>
mlir::ADORA::createBufferReusePass() {
  return std::make_unique<BufferReusePass>();
}
